spring:
  datasource:
    url: ${MYSQL_URL:jdbc:mysql://localhost:3306/db_employee}
    username: ${MYSQL_USER_NAME:root}
    password: ${MYSQL_PASSWORD:root123}
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update