spring:
  datasource:
    url: ${MYSQL_URL:jdbc:mysql://localhost:3306/db_employee}
    username: ${MYSQL_USERNAME:tit}
    password: ${MYSQL_PASSWORD:dangtit90}
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update