spring:
  datasource:
    driverClassName: org.h2.Driver
    password: root123
    url: jdbc:h2:mem:db_employee
    username: root
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
  h2:
    console.enabled: true